#! /bin/bash

## For Mac or linux perhaps
PATH=/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/davidcok/.opam/system/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/local/bin:/opt/local/sbin
export JAVA_HOME=`/usr/libexec/java_home`
##export JAVA_HOME="C:/Program Files/Java/jdk1.7.0_67"

## TODO - this is not portable across build environments
## Convert this to ant

## Need the following for jar

version=`cat ../SMTFeature/feature.xml | head | grep -v encoding | grep "version=" | sed -e 's/ //g' -e 's/version=\"//' -e 's/\"//'`
echo Building version $version
cat src/org/smtlib/resources/version.template | sed -e "s/DEV/${version}/" > src/org/smtlib/resources/version.properties
cp src/org/smtlib/resources/version.properties bin/org/smtlib/resources/version.properties

rm -rf temp
mkdir temp
echo "Manifest-Version: 1.0" > temp/manifest
echo "Main-Class: org.smtlib.SMT" >> temp/manifest
cd bin
rm -f jsmtlib.properties
"$JAVA_HOME/bin/jar" -cfm ../jSMTLIB.jar ../temp/manifest .
cp ../jsmtlib.properties .
cd ..
##ant -f javadoc.xml
##cp ../../../../texstuff/papers/SMTLIBUserGuide/SMTLIBUserGuide.pdf jSMTLIBUserGuide.pdf
##tar cf jSMTLIB.tar jSMTLIB.jar LICENSE jSMTLIBUserGuide.pdf jsmtlib.properties-template doc
##rm -f jSMTLIBUserGuide.pdf
##tar tvf jSMTLIB.tar
##rm -f jSMTLIB.tar.gz
##gzip jSMTLIB.tar

echo Build complete

export OPENJML=../../OpenJMLB/OpenJML
if [ -e $OPENJML/OpenJML ] ; then cp jSMTLIB.jar $OPENJML/OpenJML ; else echo Copy failed ; fi
if [ -e $OPENJML/OpenJMLUI ] ; then cp jSMTLIB.jar $OPENJML/OpenJMLUI ; else echo Copy failed; fi
export OPENJML=../../OpenJMLA/OpenJML
if [ -e $OPENJML/OpenJML ] ; then cp jSMTLIB.jar $OPENJML/OpenJML ; else echo Copy failed ; fi
if [ -e $OPENJML/OpenJMLUI ] ; then cp jSMTLIB.jar $OPENJML/OpenJMLUI ; else echo Copy failed; fi
echo Copies complete
