# Makefile for the gh-pages branch of smtlib/jSMTLIB, published at
# https://smtlib.github.io/jSMTLIB/
#
# Typical flow: edit tex/SMTLIBTutorial.tex, `make build` to regenerate
# SMTLIBTutorial.pdf here, commit it, then `make push` to publish.

# tex/SMTLIBTutorial.bbl is the pre-resolved bibliography, checked in as-is:
# the source's \bibliography{../bibliography/cok} points at David's private,
# much larger master bibliography, which isn't distributed here and has
# unrelated syntax errors elsewhere in the file that break bibtex. Reusing
# the existing .bbl avoids both problems; it only needs regenerating (by
# running bibtex against that master .bib, then copying the .bbl here) if
# the tutorial's own citations ever change.
#
# Uses MacTeX (/Library/TeX/texbin) explicitly: whatever MiKTeX install is
# first on PATH here is missing its hyphenation/language.dat data and fails
# outright on \usepackage[USenglish]{babel}.
TEXDIR  := tex
TEXNAME := SMTLIBTutorial
TEXBIN  := /Library/TeX/texbin

# LaTeX byproducts, gitignored, that `build` leaves behind and `clean`
# removes. Deliberately excludes $(TEXNAME).bbl, which is checked in (see
# above) and not regenerated by `build`.
GENERATED := $(addprefix $(TEXDIR)/$(TEXNAME).,aux log toc out idx ind ilg lot tcp tps fls fdb_latexmk blg pdf)

.PHONY: build push clean

# Builds SMTLIBTutorial.pdf from its LaTeX source (pdflatex, makeindex, then
# two more pdflatex passes to settle cross-references/TOC) and copies the
# result into this branch.
build:
	cd $(TEXDIR) && PATH="$(TEXBIN):$$PATH" pdflatex -interaction=nonstopmode $(TEXNAME).tex
	cd $(TEXDIR) && PATH="$(TEXBIN):$$PATH" makeindex $(TEXNAME).idx
	cd $(TEXDIR) && PATH="$(TEXBIN):$$PATH" pdflatex -interaction=nonstopmode $(TEXNAME).tex
	cd $(TEXDIR) && PATH="$(TEXBIN):$$PATH" pdflatex -interaction=nonstopmode $(TEXNAME).tex
	cp $(TEXDIR)/$(TEXNAME).pdf ./$(TEXNAME).pdf

# Removes generated files (all gitignored; see GENERATED above). Leaves the
# top-level SMTLIBTutorial.pdf alone -- that copy is the tracked, published
# artifact, not a byproduct.
clean:
	rm -f $(GENERATED)

# Publishes this branch to GitHub Pages. Refuses to push if the working
# tree isn't clean, so what's live always matches a real commit.
push:
	@if [ -n "$$(git status --porcelain)" ]; then \
		echo "Working tree is not clean -- commit or stash changes before pushing." >&2; \
		exit 1; \
	fi
	git push origin gh-pages
