success
success
success
(error "line 8 column 14: Sort mismatch at argument #2 for function (declare-fun = (Real Real) Bool) supplied sort is Int")
(error "line 9 column 14: Sort mismatch at argument #1 for function (declare-fun = (Real Real) Bool) supplied sort is Int")
(error "line 10 column 15: Sort mismatch at argument #2 for function (declare-fun >= (Real Real) Bool) supplied sort is Int")
(error "line 11 column 15: Sort mismatch at argument #2 for function (declare-fun >= (Int Int) Bool) supplied sort is Real")
