success
success
success
(error "line 4 column 14: Sort mismatch at argument #2 for function (declare-fun = (Real Real) Bool) supplied sort is Int")
(error "line 5 column 14: Sort mismatch at argument #1 for function (declare-fun = (Real Real) Bool) supplied sort is Int")
(error "line 6 column 15: Sort mismatch at argument #2 for function (declare-fun >= (Real Real) Bool) supplied sort is Int")
(error "line 7 column 15: Sort mismatch at argument #2 for function (declare-fun >= (Int Int) Bool) supplied sort is Real")
