success
success
success
success
success
(:assertion-stack-levels 0 )
(
)
success
success
(:assertion-stack-levels 1 )
(
a
)
success
success
(:assertion-stack-levels 2 )
(
a
b
)
success
(:assertion-stack-levels 1 )
(
a
)
success
success
(:assertion-stack-levels 3 )
(
a
c
)
success
(:assertion-stack-levels 1 )
(
a
)
success
(:assertion-stack-levels 1 )
(
)
success
success
success
(:assertion-stack-levels 2 )
(
e
)
success
(:assertion-stack-levels 0 )
success
success
(:assertion-stack-levels 0 )
(
)
