name: 'jSMTLIB Checkout'
description: 'A composite action that checks out the jSMTLIB repo'

## Clones jSMTLIB into jSMTLIB/ in the current working directory.

inputs:
  branch:
    description: 'The branch of jSMTLIB to checkout'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout jSMTLIB repo
      shell: bash
      run: |
        git config --global core.autocrlf input
        git clone -b ${{ inputs.branch }} --depth 1 https://github.com/smtlib/jSMTLIB
