org.smtlib.logic_path=
org.smtlib.solver_z3.exec=
org.smtlib.solver_z3_4_3.exec=
org.smtlib.solver_z3_4_8.adapter=org.smtlib.solvers.Solver_z3_4_8
org.smtlib.solver_z3_4_8.exec=
org.smtlib.solver_z3_4_8.command=
org.smtlib.solver_cvc5.exec=
org.smtlib.solver_simplify.exec=
