#!/bin/bash

## Note: Files ending in .tst are test scripts
##       Files ending in .tst.out are the corresponding expected outputs
##       Files ending in .tst.actual are the actual output if the test fails
##       Files ending in .tst.err are the expected err output if non-empty

echo $1
export solver=$1
source solvers
shift

#java -cp ../bin org.smtlib.SMT --logics ../logics --solver $@

echo ${SMT_EXE}
${SMT_EXE} $@

