; match error: non-exhaustive patterns (no variable/wildcard, not all constructors)
(set-logic ALL)
(declare-datatype Color ((red) (green) (blue)))
(declare-fun c () Color)
(assert (match c ((red true) (green false))))
