(set-logic AUFLIA)
(declare-sort B 0)
(declare-fun p () B)
(declare-fun q () B)
(declare-fun r () B)
(declare-fun f (B B) Bool)
(assert (forall ((x B)(y B)(z B)) (=> (and (f x y) (f y z)) (f x z))))
(assert (and (f p q) (f q r)))
(assert (not (f p r)))
(check-sat)
