(set-logic AUFLIA)
(declare-fun p () Bool)
(declare-fun q () Bool)
(declare-fun r () Bool)
(declare-fun f (Bool Bool) Bool)
(assert (forall ((x Bool)(y Bool)(z Bool)) (=> (and (f x y) (f y z)) (f x z))))
(assert (and (f p q) (f q r)))
(push 1)
(assert (f p r))
(check-sat)
(pop 1)
(assert (not (f p r)))
(check-sat)
