; (store a i v) has sort (Array I V), which does not match i (sort I)
(set-logic QF_AX)
(declare-sort I 0)
(declare-sort V 0)
(declare-fun i () I)
(declare-fun v () V)
(declare-fun a () (Array I V))
(assert (= i (store a i v)))
