#!/bin/bash

## Note: Files ending in .tst are test scripts
##       Files ending in .tst.out are the corresponding expected outputs
##       Files ending in .tst.actual are the actual output if the test fails
##       Files ending in .tst.err are the expected err output if non-empty

solver=$1
test=$2
source solvers


rm -f ${test}.actual
echo Running $test $solver

$SMT_EXE $test > output 2> erroutput

### Check the error output
if [ -e ${test}.err.$solver ]; then
    diff erroutput ${test}.err.${solver}
    errok=$?
elif [ -e ${test}.err ]; then
    diff erroutput ${test}.err
    errok=$?
elif [ -s erroutput ]; then
    errok=1
    echo ERROR OUTPUT was expected to be empty
    cat erroutput
else
    errok=0
fi

### Check the regular output
comparison=""
if [ -e ${test}.out.$solver ]; then
    diff -b output ${test}.out.${solver}
    diffresult=$?
    comparison=${test}.out.$solver
elif [ -e ${test}.out.$solver.bad ]; then
    diff -b output ${test}.out.${solver}.bad
    diffresult=$?
    comparison=${test}.out.$solver.bad
elif [ ! -e ${test}.out ]; then 
    echo No output file, creating one
    cat output
    mv output ${test}.out
    diffresult=1
else 
    diff -b output ${test}.out 
    diffresult=$?
fi

    if [ $diffresult == 0 ] ; then
        if [ $errok == 0 ]; then
            echo SUCCESS "                               " ${comparison}
            exit 0
        else
            ### Failing because the error output did not match
            echo FAILURE - mismatched error output
        fi
    else
        echo FAILURE - mismatched regular output
        if [ -e output ]; then mv output ${test}.actual ; fi
    fi
exit 1
