#! /bin/bash

cd "$(dirname "$0")" || exit 1
source setup
rm -f tempout
solvers="test z3"

while [[ $# -gt 0 && "$1" == --* ]]; do
    case "$1" in
        --solvers) solvers="$2"; shift 2 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

if [ $# -eq 0 ]; then
    tests=( "$TESTS"/*.tst )
else
    tests=()
    for arg in "$@"; do
        if [[ "$arg" != */* ]]; then
            tests+=( "$TESTS/$arg" )
        else
            tests+=( "$arg" )
        fi
    done
fi

echo SOLVERS $solvers

count=0
ok=0
for f in "${tests[@]}" ; do
    for solver in $solvers; do
        (( count++ ))
        ./runtest $solver "$f"
        if [ $? == 0 ]; then (( ok ++ )) ; fi
    done
done
(( fail = $count - $ok ))
if [ $fail == 0 ]; then
    echo All $count tests SUCCEEDED
else
    echo $fail FAILURES out of $count tests
fi
source version.check
