; checks the set and get of produce options
(set-option :produce-proofs true)
(get-option :produce-proofs)
(set-option :produce-proofs false)
(get-option :produce-proofs)
(set-option :produce-unsat-cores true)
(get-option :produce-unsat-cores)
(set-option :produce-unsat-cores false)
(get-option :produce-unsat-cores)
(set-option :produce-assignments true)
(get-option :produce-assignments)
(set-option :produce-assignments false)
(get-option :produce-assignments)
(set-option :produce-models true)
(get-option :produce-models)
(set-option :produce-models false)
(get-option :produce-models)
