success
success
success
success
success
success
success
success
(
error
"line 11 column 15: command is only available in interactive mode, use command (set-option :interactive-mode true)"
)
success
(
error
"line 13 column 15: command is only available in interactive mode, use command (set-option :interactive-mode true)"
)
success
(
error
"line 15 column 15: command is only available in interactive mode, use command (set-option :interactive-mode true)"
)
