; allowed to set pre-defined info
(set-info :name "x")
(get-info :name)
(set-info :authors "x")
(get-info :authors)
(set-info :version "0")
(get-info :version)
(set-info :error-behavior x)
(get-info :error-behavior)
(set-info :all-statistics x)
(get-info :all-statistics)
(set-info :reason-unknown x)
(get-info :reason-unknown)
