; checks the sorts of bit-vector functions
(set-logic QF_BV)
(declare-fun t () (_ BitVec 3))
(declare-fun x () (_ BitVec 3))
(declare-fun y () (_ BitVec 5))
(declare-fun z () (_ BitVec 8))
(assert (= (bvnot x) #b111))
(assert (= (bvneg x) #b111))
(assert (= (bvand x t) #b111))
(assert (= (bvor x x) #b111))
(assert (= (bvadd x x) #b111))
(assert (= (bvmul x x) #b111))
(assert (= (bvshl x x) #b111))
(assert (= (bvlshr x x) #b111))
(assert (= (bvudiv x x) #b111))
(assert (= (bvurem x x) #b111))
(assert (bvult x t))
(assert (= (concat x y) z))
(assert (= ((_ extract 2 4) z) x))
(assert (= #xF #b1111))
(assert (distinct #x0 #b0000))
