; tests whether get-assertions works correctly with push and pop
(set-option :interactive-mode true)
(set-logic QF_UF)
(declare-fun p () Bool)
(assert true)
(assert p)
(push 1)
(assert (or p p))
(assert false)
(get-assertions)
(pop 1)
(get-assertions)
(assert (not p))
(get-assertions)
