#! /bin/bash

rm -f tempout
if [ $# -eq 0 ]; then
    solvers="test simplify yices cvc z3 "
else
    solvers="$@"
fi

echo SOLVERS $solvers

count=0
ok=0
for solver in $solvers; do
    for f in *.tst ; do
        (( count++ ))
        ./runtest $solver $f
        if [ $? == 0 ]; then (( ok ++ )) ; fi
    done
done
(( fail = $count - $ok ))
if [ $fail == 0 ]; then
    echo All $count tests SUCCEEDED
else
    echo $fail FAILURES out of $count tests
fi
source version.check
