#! /bin/bash

SOURCEFORGE_USERNAME=davidcok

## Need to : make the documents
##         : perhaps copy the projectSet.psf file


cd `dirname $BASH_SOURCE`
cd ../..
version=0.9.7.1
WEB=SMTUpdateSite/web

echo "Using sourceforge user name $SOURCEFORGE_USERNAME"

cd SMTUpdateSite
export version=`ls -t features/* | head -1 | sed -e sxfeatures/org.smtlib.SMTFeature_xx -e sx.jarxx`
cd ..

file=`ls -t SMT/*.tar.gz | head -1`
##filedate=`echo $file | tr -d [a-zA-Z./] | tr -d '-'`
echo The current version is $version
echo The current version is $version | cat ${WEB}/README-root - > ${WEB}/README

echo "Version ${version}"

sftp $SOURCEFORGE_USERNAME,jsmtlib@web.sourceforge.net << HERE
cd htdocs
lcd ${WEB}
put indexSF.html index.html
put book.css
put style.css
lcd ../..
put ../../texstuff/papers/SMTLIBTutorial/SMTLIBTutorial.pdf
put ../../texstuff/papers/SMTLIBUserGuide/SMTLIBUserGuide.pdf jSMTLIBUserGuide.pdf
put SMT/jSMTLIB.tar.gz
cd jsmtlib-updatesite
lcd SMTUpdateSite/web
put indexUS.html index.html
put book.css
put style.css
lcd ../..
lcd SMTUpdateSite
put site.xml
put content.jar
put artifacts.jar
put features/org.smtlib.SMTFeature_${version}.jar features
put plugins/org.smtlib.*_${version}.jar plugins
lcd ..
cd /home/frs/project/j/js/jsmtlib
put SMTUpdateSite/web/README
put ../../texstuff/papers/SMTLIBUserGuide/SMTLIBUserGuide.pdf jSMTLIBUserGuide.pdf
put SMT/jSMTLIB.tar.gz

quit
HERE

echo "Transfer completed"
exit
