success
(error "line 5 column 36: logic does not support quantifiers")
success
success
success
success
(error "line 10 column 21: logic does not support nonlinear arithmetic")
success
success
success
success
success
success
(error "line 17 column 25: logic does not support uninterpreted functions")
success
success
success
success
success
(error "line 23 column 36: logic does not support quantifiers")
success
success
success
success
(error "line 28 column 21: logic does not support nonlinear arithmetic")
success
success
success
success
success
success
(error "line 35 column 30: logic does not support quantifiers")
success
success
success
success
success
success
(error "line 42 column 36: logic does not support quantifiers")
success
success
success
success
success
success
success
success
(error "line 51 column 21: logic only supports difference arithmetic")
