; Issue #47: characterizes externally observable behavior (quantifier rejection, linearity,
; function/sort-declaration permissions) of QF_LIA/QF_UFLIA/QF_UFBV/QF_UFIDL, confirming a
; sibling-class-reuse refactor of their logic/ restriction classes did not change behavior.
(set-logic QF_LIA)
(assert (forall ((y Int)) (>= y 0)))
(reset)
(set-logic QF_LIA)
(declare-const x Int)
(declare-const y Int)
(assert (= (* x y) 0))
(reset)
(set-logic QF_LIA)
(declare-const x Int)
(assert (= (* 3 x) 0))
(reset)
(set-logic QF_LIA)
(declare-fun f (Int) Int)
(reset)
(set-logic QF_LIA)
(declare-sort S 0)
(reset)
(set-logic QF_UFLIA)
(assert (forall ((y Int)) (>= y 0)))
(reset)
(set-logic QF_UFLIA)
(declare-const x Int)
(declare-const y Int)
(assert (= (* x y) 0))
(reset)
(set-logic QF_UFLIA)
(declare-fun f (Int) Int)
(declare-sort S 0)
(reset)
(set-logic QF_UFBV)
(assert (forall ((y Bool)) y))
(reset)
(set-logic QF_UFBV)
(declare-fun f (Bool) Bool)
(declare-sort S 0)
(reset)
(set-logic QF_UFIDL)
(assert (forall ((y Int)) (>= y 0)))
(reset)
(set-logic QF_UFIDL)
(declare-fun f (Int) Int)
(declare-sort S 0)
(reset)
(set-logic QF_UFIDL)
(declare-const x Int)
(declare-const y Int)
(assert (= (+ x y) 3))
