success
success
success
success
success
(error "line 7 column 21: unknown sort 'BitVecx'")
(error "Expected a numeral here, instead of a symbol")
(error "Expected a numeral here, instead of a )")
(error "line 8 column 31: expecting one integer parameter to bit-vector sort")
(error "line 9 column 18: invalid function application, sort mismatch on argument at position 2")
(error "line 10 column 17: invalid function application, sort mismatch on argument at position 2")
(error "line 11 column 14: invalid function application, sort mismatch on argument at position 2")
