success
success
success
(error "line 4 column 17: unknown constant bvnego ((_ BitVec 4)) ")
(error "line 5 column 20: unknown constant bvuaddo ((_ BitVec 4) (_ BitVec 4)) ")
(error "line 6 column 20: unknown constant bvsaddo ((_ BitVec 4) (_ BitVec 4)) ")
(error "line 7 column 20: unknown constant bvumulo ((_ BitVec 4) (_ BitVec 4)) ")
(error "line 8 column 20: unknown constant bvsmulo ((_ BitVec 4) (_ BitVec 4)) ")
sat
