; QF_LIA forbids quantifiers, nonlinear arithmetic, UF, and new sorts
(set-logic QF_LIA)
(declare-const x Int)
(declare-const y Int)
(declare-const z Int)
(assert (forall ((a Int)) (>= a 0)))
(assert (= y (* x x)))
(declare-fun f (Int) Int)
(declare-sort S 0)
; div, mod, abs are nonlinear (covers Logic.isLinearInteger div/mod/abs branches)
(assert (= z (div x y)))
(assert (= z (mod x y)))
(assert (= z (abs x)))
; (* (- x) y) is nonlinear because (- x) is not an integer constant (covers isInteger false branch)
(assert (= z (* (- x) y)))
