; QF_LRA: quantifier-free linear real arithmetic
(set-logic QF_LRA)
(declare-const x Real)
(declare-const y Real)
(assert (= y (+ x 1.0)))
(assert (= y (* 3.0 x)))
(assert (>= x 0.0))
; define-fun and define-sort are allowed (covers noFunctions/noSorts pass branches)
(define-fun scale ((r Real)) Real (* 2.0 r))
(define-sort MyReal () Real)
; valid constant division (covers LRA.validExpression / pass path, isConst IDecimal arg of /)
(assert (= y (/ 1.0 2.0)))
; negative decimal as constant (covers LRA.isConst - with IDecimal)
(assert (= y (* (- 3.0) x)))
; (+ x 1.0) as *-arg: isConst((+ x 1.0)) falls to default return false (covers isConst line 41)
(assert (= y (* (+ x 1.0) 2.0)))
