; QF_EIA: closed quantifier-free formulas over Ints with free constants.
; Like QF_NIA but exponentiation (**) is permitted.
(set-logic QF_EIA)
(declare-const x Int)
(declare-const y Int)
(assert (= y (+ x 1)))
(assert (= y (- x 1)))
(assert (= y (* x x)))
(assert (= y (* 3 x)))
(assert (>= x 0))
(assert (<= x y))
(assert (= y (- x)))
(assert (distinct x y))
; exponentiation is permitted (unlike QF_NIA)
(assert (= y (** x 2)))
(assert (= y (** 2 x)))
(assert (>= (** x 3) 0))
; define-sort alias is allowed (covers checkSortDeclaration pass path)
(define-sort MyInt () Int)
